### ISSUE TITLE
feature: allow for networks to be added/removed from the GUI 

### ISSUE THREAD

**Issue by yourbuddyconner** [nomad-xyz/nomad-app#259]
We're going to be deploying core and bridge contracts to many a network and we'd like to have optionality to not include these networks in the GUI, despite their configuration being present in the config module.

**Comment by Imti** [comment]
We could use the "bridgeGui" field in the config and add a list of visible networks (ie: `['kovan', 'rinkeby', 'moonbasealpha']`)

Do we have a list of ones we wanna show? I'm assuming it's probably just all the ones we have in the config rn

**Comment by ErinHales** [comment]
Deadline:
We're doing new production deploy Tuesday, so should have this in by EOD Monday.

I think for now (since we don't have the full configuration refactor) we should test removing 1 testnet network from GUI configs.  I believe we'll still need to register a provider for this network, but otherwise I think it should work fine.

**Comment by Imti** [comment]
One other thing we could do instead of the above, is to just not add the networks we wanna hide to the object below. This way we keep bridgeGui clean and we only need to do one thing when we wanna show a new network: add the network object network key with the display name and native token symbol

```
"bridgeGui": {
    "rinkeby": {
      "displayName": "Rinkeby",
      "nativeTokenSymbol": "ETH"
    },
    "kovan": {
      "displayName": "Kovan",
      "nativeTokenSymbol": "kETH"
    },
    "moonbasealpha": {
      "displayName": "Moonbase Alpha",
      "nativeTokenSymbol": "DEV"
    },
    "milkomedatestnet": {
      "displayName": "Milkomeda Testnet",
      "nativeTokenSymbol": "milkADA"
    },
    "evmostestnet": {
      "displayName": "Evmos Testnet",
      "nativeTokenSymbol": "tEVMOS"
    }
  }
```

Worst case, we can quickly filter these on the frontend.

**Comment by Imti** [comment]
This is done as part of the integrate config into gui PR (https://github.com/nomad-xyz/nomad-app/pull/272)
