### ISSUE TITLE
app.nomad.xyz doesn't show Open Graph info

### ISSUE THREAD

**Issue by odyslam** [nomad-xyz/nomad-app#267]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/13405632/163009457-e5f1bde6-8200-49d9-a425-6caf12a2f187.png">

Propably a super easy fix, by just adding the meta tags to the <HEAD></HEAD> part of the app:

e.g https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by Imti** [comment]
Fixed by these commits: https://github.com/nomad-xyz/nomad-app/compare/25d3996039540504f3a9a0dfc30fbd430fd69baf...68537b18e189e180d50b5fee528a1c590dcadbfd

Opengraph was correctly set but twitter specific metatags needed an absolute url for the twitter card image.

Fixed on dev, will go out with next prod release.
