### ISSUE TITLE
Include flow for converting madFRAX to canonical FRAX

### ISSUE THREAD

**Issue by pranaymohan** [nomad-xyz/nomad-app#369]
### Describe the feature you would like

FRAX is a unique token in that each FRAX deployment on destination chains is deployed by the Frax team. They then whitelist bridges to be able to do an in-place conversion of the bridged FRAX representation to the canonical representation deployed by the core team. This means that apps on the destination chains are encouraged to use the canonical representation rather than bridged ones.

However, when a user bridges via Nomad, they receive the Nomad representation of FRAX, aka madFRAX. They then need to go to the Frax UI to convert this into canonical FRAX. It would be a much better user experience if the Nomad UI included this last step so that the user was able to convert madFRAX into canonical FRAX without having to do a bunch of research and leave the Nomad app.

### Additional context

- Link on canonical FRAX: https://docs.frax.finance/cross-chain/bridge

**Comment by James8T** [comment]
ETH recovery rate will be near zero as almost all $ETH are hold by 1 hacker address who will NOT return funds. Also I receive death threats for debt I have but you have lost my money in your custodian-bridge ( team control via multisig proxy crucial updates ). ☠️☠️💀💀

Who said « users first » « security first » and misleaded users!??!!? Nomad founders. Take responsibilities !!!! I can not pay scholarships to my son because of you! $

——> I want You and founders of Nomad contribute with your own money. You are paid high salaries, have ton of saving to have worked in High marketcap projects like Celo and Storj .

ETHmad holders will have recovery near 0%. Only 1-2 hackers hold the stolen ETH, probably will never been returned.

Here details on Medium post : https://medium.com/@jamestrulard/explore-solutions-to-rise-recovery-of-nomad-bridge-exploit-victims-b3d8058d9ddb

**Comment by ErinHales** [comment]
Outdated
